{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-coturn
  labels:
{{ include "labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-coturn
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.cpu.targetAverageUtilization }}
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          averageUtilization: {{ .Values.autoscaling.cpu.targetAverageUtilization }}
          type: Utilization
    {{- end }}
    {{- if .Values.autoscaling.memory.targetAverageUtilization }}
    - type: "Resource"
      resource:
        name: "memory"
        target:
          averageUtilization: {{ .Values.autoscaling.memory.targetAverageUtilization }}
          type: Utilization
    {{- end }}
{{- end }}
