---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := $.Values.service.annotations }}
      "{{ $key }}": "{{ tpl $value $ }}"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: turn-tcp
      port: {{ .Values.coturn.ports.listening }}
      protocol: TCP
      targetPort: {{ .Values.coturn.ports.listening }}
    - name: turn-udp
      port: {{ .Values.coturn.ports.listening }}
      protocol: UDP
      targetPort: {{ .Values.coturn.ports.listening }}
    {{- if .Values.certificate.enabled }}
    - name: turn-tcp-tls
      port: {{ .Values.coturn.ports.tlsListening }}
      protocol: TCP
      targetPort: {{ .Values.coturn.ports.tlsListening }}
    - name: turn-udp-tls
      port: {{ .Values.coturn.ports.tlsListening }}
      protocol: UDP
      targetPort: {{ .Values.coturn.ports.tlsListening }}
    {{- end }}
    {{- range $i, $port := untilStep (.Values.coturn.ports.min | int) (.Values.coturn.ports.max | int) 1 }}
    - name: "session-{{ $i }}"
      port: {{ $port }}
      protocol: "UDP"
      targetPort: {{ $port }}
    {{- end }}

    
